import OBR from 'https://esm.unpkg.com/@owlbear-rodeo/sdk@3.1.0';
import {CHARACTERS,defaultRuntimeState} from './characters.js';
import {rollSimple} from './roll.js';
import {CHAT_CHANNEL,ROOM_STATE_KEY,RECENT_KEY,MAX_MESSAGE_LENGTH,escapeHtml,makeId,mergeEntries,relativeTime} from './chat-core.js';
import {normalizeRuntimeState} from './core-shared.js';

const $=s=>document.querySelector(s);
const SHEETS_BASE_URL='https://op2fichas.onrender.com';
const GM_ACCENT='#7757c8';
const GM_ROSTER_MODAL='com.op2.playtest.chat/open-fichas';
const SHEET_MODAL='com.op2.playtest.fichas/sheet';
const state={role:'PLAYER',playerId:'preview',connectionId:'preview',roomState:defaultRuntimeState(),entries:[],historyParts:new Map(),selectedSides:20,count:1,toastTimer:null};
const dieImg=s=>`<img class="die-asset" src="./assets/dice/d${Number(s)}.png" alt="d${Number(s)}" />`;

function assignedId(){return Object.keys(CHARACTERS).find(id=>state.roomState.assignments?.[id]?.playerId===state.playerId)||null}
function authorDisplay(){const id=assignedId();return id?CHARACTERS[id].name:(state.role==='GM'?'Mestre':'Jogador')}
function getAccent(){const id=assignedId();return id?CHARACTERS[id].accent:(state.role==='GM'?GM_ACCENT:'#c6442b')}
function setTheme(){const id=assignedId(),c=id?CHARACTERS[id]:null;const accent=getAccent();document.documentElement.style.setProperty('--accent',accent);document.documentElement.dataset.role=state.role==='GM'?'gm':'player';$('#identity').textContent=c?`${c.name} · ${c.profile}`:(state.role==='GM'?'MESTRE':'SEM FICHA')}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.remove('hidden');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>el.classList.add('hidden'),2800)}
function canDelete(e){return state.role==='GM'||e.authorId===state.playerId}
function resultState(r){if(r.criticalFailure)return['FALHA CRÍTICA','critical-failure'];if(r.criticalSuccess)return['SUCESSO CRÍTICO','critical-success'];if(r.success===false)return['FALHA','failure'];if(r.success===true)return['SUCESSO','success'];return['ROLAGEM','neutral']}

function resultCard(e){
  const r=e.result||{};const [status,cls]=resultState(r);const del=canDelete(e)?`<button class="delete" data-delete="${escapeHtml(e.id)}" title="Apagar">×</button>`:'';
  return `<article class="result-card ${cls}" style="--msg-accent:${e.accent||'#c6442b'}"><div class="result-head"><div><div class="result-author">${escapeHtml(e.authorName)}</div><div class="result-title">${escapeHtml(r.label||'Teste')}</div></div><div class="result-time"><span>${relativeTime(e.createdAt)}</span>${del}</div></div><div class="result-dice">${(r.dice||[]).map(d=>`<div class="result-die"><span class="result-die-source">${escapeHtml(d.source||`d${d.sides}`)}</span><div class="result-die-value">${dieImg(d.sides)}<strong>${d.value}</strong></div></div>`).join('')}</div><div class="result-summary"><div class="result-total"><span>RESULTADO</span><strong>${r.total??0}</strong></div><span class="result-status">${status}</span></div>${(r.dice||[]).length>3?'<div class="result-note">OS TRÊS MAIORES RESULTADOS FORAM SOMADOS.</div>':''}</article>`;
}
function simpleRollCard(e){const r=e.roll||{};const del=canDelete(e)?`<button class="delete" data-delete="${escapeHtml(e.id)}" title="Apagar">×</button>`:'';return `<article class="result-card neutral" style="--msg-accent:${e.accent||'#c6442b'}"><div class="result-head"><div><div class="result-author">${escapeHtml(e.authorName)}</div><div class="result-title">${escapeHtml(r.label||'Rolagem livre')}</div></div><div class="result-time"><span>${relativeTime(e.createdAt)}</span>${del}</div></div><div class="simple-roll-values">${(r.values||[]).map(v=>`<span class="simple-die">${dieImg(r.sides)}<strong>${v}</strong></span>`).join('')}</div><div class="free-result"><span>RESULTADO</span><strong>${r.total??0}</strong></div></article>`}
function renderFeed(){const feed=$('#feed');if(!state.entries.length){feed.innerHTML='<div class="empty-feed">A investigação ainda não começou.</div>';return}feed.innerHTML=state.entries.map(e=>{if(e.type==='message'){const del=canDelete(e)?`<button class="delete" data-delete="${escapeHtml(e.id)}" title="Apagar">×</button>`:'';return `<article class="message" style="--msg-accent:${e.accent||'#c6442b'}"><div class="message-head"><span class="author">${escapeHtml(e.authorName)}</span><span class="time"><span>${relativeTime(e.createdAt)}</span>${del}</span></div><div class="message-text">${escapeHtml(e.text)}</div></article>`}if(e.type==='simple-roll')return simpleRollCard(e);return resultCard(e)}).join('');feed.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',()=>deleteEntry(btn.dataset.delete)));feed.scrollTop=feed.scrollHeight}
function mergeAndRender(entries){state.entries=mergeEntries(state.entries,entries);renderFeed()}
function sendEntry(entry){mergeAndRender([entry]);if(OBR.isAvailable)OBR.broadcast.sendMessage(CHAT_CHANNEL,{type:'submit',entry},{destination:'ALL'}).catch(()=>toast('Não foi possível sincronizar a mensagem.'))}
function deleteEntry(id){state.entries=state.entries.filter(e=>e.id!==id);renderFeed();if(OBR.isAvailable)OBR.broadcast.sendMessage(CHAT_CHANNEL,{type:'delete',entryId:id},{destination:'ALL'}).catch(()=>{})}
function submitMessage(){const input=$('#message'),text=input.value.trim();if(!text)return;const command=text.match(/^\/r\s+(\d+)d(\d+)([+-]\d+)?$/i);if(command){const count=Math.max(1,Math.min(12,Number(command[1])||1)),sides=Number(command[2]),bonus=Number(command[3]||0);if([4,6,8,10,12,20].includes(sides)){const roll=rollSimple({count,sides,bonus,label:'Rolagem livre'});sendEntry({id:makeId(),type:'simple-roll',createdAt:Date.now(),authorId:state.playerId,authorName:authorDisplay(),accent:getAccent(),roll});input.value='';return}}sendEntry({id:makeId(),type:'message',createdAt:Date.now(),authorId:state.playerId,authorName:authorDisplay(),accent:getAccent(),text:text.slice(0,MAX_MESSAGE_LENGTH)});input.value=''}
function renderDiceTray(){const sides=[4,6,8,10,12,20];$('#diceButtons').innerHTML=sides.map(s=>`<button class="die-btn ${state.selectedSides===s?'active':''}" data-side="${s}" aria-label="Selecionar d${s}">${dieImg(s)}<span>D${s}</span></button>`).join('');$('#diceButtons').querySelectorAll('[data-side]').forEach(btn=>btn.addEventListener('click',()=>{state.selectedSides=Number(btn.dataset.side);renderDiceTray()}));$('#countValue').textContent=state.count}
function freeRoll(){const bonus=Number($('#freeBonus').value||0);const roll=rollSimple({sides:state.selectedSides,count:state.count,bonus,label:`${state.count}d${state.selectedSides}${bonus?bonus>0?` + ${bonus}`:` - ${Math.abs(bonus)}`:''}`});sendEntry({id:makeId(),type:'simple-roll',createdAt:Date.now(),authorId:state.playerId,authorName:authorDisplay(),accent:getAccent(),roll})}
async function openSheet(){
  const id=assignedId();
  if(!OBR.isAvailable){location.href=id?`${SHEETS_BASE_URL}/sheet.html?id=${id}&from=chat`:`${SHEETS_BASE_URL}/?from=chat`;return}
  try{
    if(state.role==='GM'){await OBR.modal.open({id:GM_ROSTER_MODAL,url:`${SHEETS_BASE_URL}/?from=chat&modalId=${encodeURIComponent(GM_ROSTER_MODAL)}`,fullScreen:true});return}
    if(!id){toast('O mestre ainda não atribuiu uma ficha a você.');return}
    await OBR.modal.open({id:SHEET_MODAL,url:`${SHEETS_BASE_URL}/sheet.html?id=${encodeURIComponent(id)}&from=chat`,fullScreen:true});
  }catch(e){console.error(e);toast('Não foi possível abrir a ficha.')}
}
async function requestHistory(){const requestId=makeId();state.historyParts.set(requestId,{parts:[],total:null});await OBR.broadcast.sendMessage(CHAT_CHANNEL,{type:'request-history',requestId},{destination:'ALL'}).catch(()=>{})}
function onChatEvent(event){const d=event.data||{};if(d.type==='persisted-entry'&&d.entry){mergeAndRender([d.entry]);return}if(d.type==='deleted'&&d.entryId){state.entries=state.entries.filter(e=>e.id!==d.entryId);renderFeed();return}if(d.type==='history-part'&&d.targetConnectionId===state.connectionId){let bag=state.historyParts.get(d.requestId);if(!bag){bag={parts:[],total:d.total};state.historyParts.set(d.requestId,bag)}bag.total=d.total;bag.parts[d.index]=d.entries||[];if(bag.parts.filter(Boolean).length===bag.total){mergeAndRender(bag.parts.flat());state.historyParts.delete(d.requestId)}}}
async function setup(){renderDiceTray();renderFeed();$('#message').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submitMessage()}});$('#freeRoll').addEventListener('click',freeRoll);$('#countMinus').addEventListener('click',()=>{state.count=Math.max(1,state.count-1);renderDiceTray()});$('#countPlus').addEventListener('click',()=>{state.count=Math.min(12,state.count+1);renderDiceTray()});$('#openSheet').addEventListener('click',openSheet);if(!OBR.isAvailable){$('#loading').classList.add('hidden');state.role='GM';setTheme();return}await new Promise(r=>OBR.onReady(r));[state.role,state.connectionId]=await Promise.all([OBR.player.getRole(),OBR.player.getConnectionId()]);state.playerId=OBR.player.id;const meta=await OBR.room.getMetadata();state.roomState=normalizeRuntimeState(meta[ROOM_STATE_KEY]);if(Array.isArray(meta[RECENT_KEY]?.entries))mergeAndRender(meta[RECENT_KEY].entries);setTheme();OBR.broadcast.onMessage(CHAT_CHANNEL,onChatEvent);OBR.room.onMetadataChange(meta=>{if(meta[ROOM_STATE_KEY]){state.roomState=normalizeRuntimeState(meta[ROOM_STATE_KEY]);setTheme()}if(Array.isArray(meta[RECENT_KEY]?.entries))mergeAndRender(meta[RECENT_KEY].entries)});await OBR.action.setWidth(450).catch(()=>{});await requestHistory();$('#loading').classList.add('hidden')}
setup().catch(e=>{console.error(e);$('#loading').textContent=`ERRO · ${e.message||e}`});
